import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { AlertTriangle } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Domain Expired | risenrestore.org" },
      {
        name: "description",
        content:
          "The domain risenrestore.org has expired.",
      },
    ],
  }),
  component: DomainExpiredPage,
});

function DomainExpiredPage() {
  return (
    <div className="min-h-screen bg-[#f3f4f6] flex items-center justify-center px-4">

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: .5 }}
        className="w-full max-w-4xl bg-white border rounded-md shadow-sm overflow-hidden"
      >

        {/* Header */}

        <div className="bg-[#1f2937] px-6 py-5 text-white border-b">
          <h1 className="text-xl font-semibold">
            Domain Expired
          </h1>
        </div>

        {/* Body */}

        <div className="p-8">

          <div className="flex items-start gap-4">

            <div className="mt-1">
              <AlertTriangle
                className="text-yellow-500"
                size={35}
              />
            </div>

            <div>

              <h2 className="text-2xl font-semibold text-gray-900">
                risenrestore.org
              </h2>

              <p className="mt-3 text-gray-600 leading-7">
                The domain you are trying to access has expired and may no
                longer be active.
              </p>

              <p className="mt-4 text-gray-600 leading-7">
                If you are the owner of this domain, renewal may be required
                to restore website and email services.
              </p>

            </div>

          </div>

          {/* Info Box */}

          <div className="mt-8 rounded border bg-gray-50 p-5">

            <h3 className="font-semibold text-gray-800">
              Possible reasons:
            </h3>

            <ul className="mt-3 space-y-2 text-gray-600 text-sm list-disc ml-5">
              <li>Domain registration period has ended</li>
              <li>Renewal payment is pending</li>
              <li>DNS configuration issue</li>
              <li>Temporary registrar suspension</li>
            </ul>

          </div>

          {/* Footer */}

          <div className="mt-10 border-t pt-5 text-sm text-gray-500 flex justify-between flex-wrap gap-2">

            <span>
              Generated by Domain Parking Service
            </span>

            <span>
              Reference ID: RNR-2026-8472
            </span>

          </div>

        </div>
      </motion.div>

    </div>
  );
}
